config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/help'
  
  
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
  resources :topics do
    resources :posts
  end
  
  resources :favorites
  
  resources :comments, only: [:create]
  
  #get 'favorites/index'
  #post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  
  belongs_to :user
  belongs_to :topic
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  belongs_to :user
  
  mount_uploader :image,ImageUploader
  
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
  has_many :posts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length:{maximum: 15}
    validates :email, presence: true
    validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
    validates :password, length:{in:8..32}
    #validates :password, format:{with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i}
    
    has_many :topics
    has_many :favorites
    has_many :favorite_topics, through: :favorites,source:'topic'
    has_many :posts, dependent: :destroy
    has_many :comments
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger
  
  include CommonActions
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/common_actions.rb
module CommonActions
  extend ActiveSupport::Concern
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
  favorite = Favorite.new
  favorite.user_id = current_user.id
  favorite.topic_id = params[:topic_id]
  
    if favorite.save
      redirect_to topics_path,success: 'お気に入りに登録しました'
    else
      redirect_to topics_path,danger: 'お気に入りの登録に失敗しました'
    end
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    favorite.destroy
    redirect_to topics_path, danger: 'お気に入りを取り消しました'
    #redirect_to("/topics/#{params[:topic_id]}")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    @topic_id = params[:topic_id]
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new
    @post.topic_id = params[:topic_id]
    @post.content = params[:content]
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to topics_path,success: 'コメントに成功しました'
    else
      flash.now[:danger] = "コメントに失敗しました"
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path,success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info:'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def user_params
    params.require(:user).permit(:name, :eamil, :passworf, :password_confirmation)
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
    @posts = Post.where(topic_id: params[:topic_id])
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    
    if  @topic.save
      redirect_to topics_path,success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(user_id: @current_user.id, topic_id: params[:topic_id])
    @favorite.destroy if favorite.present?
    redirect_to topics_path, success: 'お気に入りを取り消しました'
    #redirect_to("/topics/#{params[:topic_id]}")
  end
  
  private
  def topic_params
    params.require(:topic).permit(:image,:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include CommonActions
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
    <div class="contianer">
        <% @favorite_topics.each do |topic| %>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="topic-index-single">
                        <h2 class="topic-author">
                            <%= topic.user.name %>
                        </h2>
                        <%= image_tag topic.image.url %>
                        
                        <%= link_to new_topic_post_path(topic_id: topic.id), method: :get do %>
                        <%= image_tag 'icons/comment.png',class: 'topic-index-icon' %>
                        <% end %>
                        
                        
                        <% if !topic.like_users.include?(current_user) %>
                          <%= link_to likes_path(topic_id: topic.id), method: :post do %>
                               <i class="far fa-heart like-btn" ></i>
                        　<% end %>
                        <% else %>
                          <%= link_to likes_path(topic_id: topic.id), method: :delete do %>
                                <i class="fas fa-heart unlike-btn"></i>
                        　<% end %>
                        <% end %>
                        <%= topic.like_users.count %>
                        
                        
                        
                        <p class="topic-text">
                            <%= topic.description %>
                        </p>
                        
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">コメント投稿</h1>
        
        <%= form_with url: topic_posts_path ,local: true do |f| %>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>

          <% if logged_in? %>
            <%= f.submit 'コメント送信', class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
 <%= form_for @post do |f| %>
   <%= f.text_field :content %>
   <%= f.submit %>
 <% end %>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
    <div class="container">
        <% @topics.each do |topic| %>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="topic-index-single">
                    <h2 class="topic-author">
                        <%= topic.user.name %>
                    </h2>
                    <%= image_tag topic.image.url %>
        
                   <% if !topic.favorite_users.include?(current_user) %>
                      <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                        <i class="fa fa-heart like-btn" ></i>
                      <% end %>
                   <% else %>
                      <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                        <i class="fa fa-heart unlike-btn" ></i>
                      <% end %>
                   <% end %>
                   <%= topic.favorite_users.count %>
                   <%= link_to new_topic_post_path(topic_id: topic.id), method: :get do %>
                        <%= image_tag 'icons/comment.png',class: 'topic-index-icon' %>
                   <% end %>
                    <p class="topic-text">
                        <h3><%= topic.description %></h3>
                        <% topic.posts.each do |post| %>
                        <%= post.user.name %><br>
                        <%= post.content %>
                        <p>--------------------</p>
                        <% end %>
                    </p>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center">Add Picture</h1>
                <%= form_for @topic do |f| %>
                <div class="form-group">
                    <%= f.label :image %>
                    <%= f.file_field :image %>
                </div>
                <div class="form-group">
                    <%= f.label :description %>
                    <%= f.text_area :description,class: 'form-control' %>
                </div>
                <% if logged_in? %>
                <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8 users-new-container">
                <h1 class="text-center text-white">Sign up</h1>
                <%= form_for @user do |f| %>
                <div class="form-group">
                    <%= f.label :name, class: 'text-white' %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <div class="form-group">
                        <%= f.label :email, class: 'text-white' %>
                        <%= f.text_field :email, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :password, class: 'text-white' %>
                    <%= f.password_field :password, class: 'form-control' %>
                </div>
                <div class="form-group">
                        <%= f.label :password_confirmation, class: 'text-white' %>
                        <%= f.password_field :password_confirmation, class: 'form-control' %>
                </div>

                <%= f.submit "登録", class: 'btn-block btn-white' %>
                <% end %>
                <%= link_to 'ログインはこちら', 'login_path',class: 'text-white' %>
            </div>
        </div>
    </div>
</div>